sudo: required
services:
  - docker

before_install:
  - docker build -t scotpfleghaar/docker-react -f Dockerfile.docker .

script:
  - docker run scotpfleghaar/docker-react npm run test -- --coverage
